### ISSUE TITLE
Mistake in the example code

### ISSUE THREAD

**Issue by kuriositeetti** [speechly/browser-client#21]
### Describe the bug
There is a mistake in the example code. The API does not return `isFinalized`. The correct param to use is `isFinal` that the API returns.

### To Reproduce
Go to https://github.com/speechly/browser-client/blob/master/examples/src/index.js#L28

### Expected behaviour
It should say `segment.isFinal` instead of `segment.isFinalized`

**Comment by radiohead** [comment]
Hey @kuriositeetti, thanks for reporting the bug!

The example has now been moved to a separate repository (https://github.com/speechly/browser-client-example) and converted to TypeScript to prevent issues like this one.

The PR #24 addresses this by removing the example from this repo.
